//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBankasi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BireyselMusteriUrunleri
    {
        public int BireyselMusteriUrunleriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string IBAN { get; set; }
        public string HesapNumarasi { get; set; }
        public Nullable<int> BireyselMusteriID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    }
}
