//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBankasi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faturalar
    {
        public int FaturalarID { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<System.TimeSpan> FaturaSaati { get; set; }
        public Nullable<int> MusteriTuruID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> OdemePlaniID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    }
}
