//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBankasi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int GiderlerID { get; set; }
        public Nullable<int> SubeGiderTuruID { get; set; }
        public Nullable<System.DateTime> Tarihi { get; set; }
        public Nullable<decimal> Miktari { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Faizlimi { get; set; }
        public Nullable<decimal> FaizOrani { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    }
}
