//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBankasi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelMaaslari
    {
        public int PersonelMaaslarID { get; set; }
        public Nullable<System.DateTime> MaasBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> MaasBitisTarihi { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    }
}
