//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBankasi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelGorevYerleri
    {
        public int PersonelGorevYerleriID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<int> GorevID { get; set; }
        public Nullable<int> SubeID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    }
}
