//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBankasi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subeler
    {
        public int SubelerID { get; set; }
        public string SubeAdi { get; set; }
        public string SubeKodu { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public Nullable<int> ilID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public string Adres { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    }
}
