//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBankasi.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunlerID { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunTuruID { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    }
}
